# =============================================
# PROFIL DEV — NE JAMAIS COMMITTER CE FICHIER
# =============================================

# Serveur Port
server.port=8080

# H2 Database (Base de données en mémoire au lieu de PostgreSQL)
spring.datasource.url=jdbc:h2:mem:facturation_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Activation de la console H2 pour voir la base (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT — clé secrète longue (min 256 bits)
jwt.secret=c2VjcmV0LWtleS10cmVzLWxvbmd1ZS1wb3VyLXBmZS1mYWN0dXJhdGlvbi0yMDI0
jwt.expiration=86400000

# Logs
logging.level.com.pfe.facturation=DEBUG
