# Profil actif : dev
spring.profiles.active=dev

# Nom de l'application
spring.application.name=facturation-app

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===== IA Gemini =====
# Définir la variable d'environnement GEMINI_API_KEY avant de lancer le backend
gemini.api.key=AIzaSyDEZ4CHGcE5lnHpEbmYRaPY7v_MwRVWbZE
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent

# ===== Email (Gmail SMTP) =====
# Remplacez par votre adresse Gmail et votre mot de passe d'application Google
# Pour créer un mot de passe d'application : https://myaccount.google.com/apppasswords
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohamedalibriki2004@gmail.com
spring.mail.password=xoyincbqaaksfrpl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
# Adresse expéditrice (doit correspondre à spring.mail.username)
app.mail.from=mohamedalibriki2004@gmail.com
app.mail.from-name=Application Facturation
